apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: ${GF_DATASOURCE_PROMETHEUS_URL}
    isDefault: true

  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: ${GF_DATASOURCE_ALERTMANAGER_URL}
    isDefault: false
    jsonData:
      implementation: prometheus