global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["172.31.23.21:9093"]

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'dashboard-app'
    static_configs:
      - targets: ['app:3000']
